version: "2"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  frontend:
    build: ./front-end
    ports:
      - "3000:80" # Frontend will be accessible on port 3000 on the host
    environment:
      - FRONTEND_URL=${VITE_API_HOST}
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
